# Generated by Django 5.1.6 on 2025-02-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='myApp.ingredient'),
        ),
    ]
