# Generated by Django 5.1.6 on 2025-02-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_recipe_average_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='average_rating',
        ),
    ]
